config/routes.rb
Rails.application.routes.draw do
  root :to => 'stations#index'

  resources :stations
  resources :lines
  resources :stops
end

app/models/line.rb
class Line < ActiveRecord::Base

  validates :name, presence: :true

  has_many :stops
  has_many :stations, :through => :stops

end

app/models/station.rb
class Station < ActiveRecord::Base

  validates :name, presence: :true

  has_many :stops
  has_many :lines, :through => :stops

end

app/models/stop.rb
class Stop < ActiveRecord::Base

  validates :line_id, presence: :true, numericality: :true
  validates :station_id, presence: :true, numericality: :true

  belongs_to :line
  belongs_to :station

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController


  def new
    @line = Line.new
  end

  def create
    @line = Line.create(params[:line])
    if @line.valid?
      flash[:notice] = "Your new line has been added."
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def show
    @line = Line.find(params[:id])
  end

  def edit
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    @line.update(params[:line])
    if @line.valid?
      flash[:notice] = "Your line has been updated."
      redirect_to stations_path
    else
      render 'edit'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy
    flash[:notice] = "This line has been deleted"
    redirect_to stations_path
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @lines = Line.all
    @stations = Station.all
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.create(params[:station])
    if @station.valid?
      flash[:notice] = "Your new station has been added."
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def show
    @station = Station.find(params[:id])
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])
    @lines = @station.lines
    @station.update(params[:station])
    if @station.valid?
      flash[:notice] = "Your station has been updated."
      redirect_to stations_path
    else
      render 'edit'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    flash[:notice] = "This station has been deleted"
    redirect_to stations_path
  end

end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  def index
    @lines = Line.all
    @stations = Station.all
    @stops = Stop.all
  end

  def new
    @station = Station.find(params[:station_id])
    @stop = Stop.new
  end

  def create
    @stop = Stop.create(params[:stops])
    if @stop.valid?
      flash[:notice] = "Your new stop has been added."
      redirect_to stations_path
    else
      render "new"
    end
  end

  def show
    @stop = Stop.find(params[:id])
  end

  def edit
    @stop = Stop.find(params[:id])
  end

  def update
    @stop = Stop.find(params[:id])
    @stop.update(params[:stop])
    if @stop.valid?
      flash[:notice] = "Your stop has been updated."
      redirect_to stops_path
    else
      render 'edit'
    end
  end

  def destroy
    @stop = Stop.find(params[:id])
    @stop.destroy
    flash[:notice] = "This stop has been deleted"
    redirect_to stops_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_helper.rb
module LineHelper
end

app/helpers/station_helper.rb
module StationHelper
end

app/helpers/stop_helper.rb
module StopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusSchedule</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

</body>
</html>

app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/lines/edit.html.erb
<p><%= link_to "Home", root_url %></p>
<h1>Edit Line</h1>

<%= render 'form' %>

app/views/lines/new.html.erb
<%= content_for(:title, "New line | Bus Schedule") %>

<h1>Add a Line:</h1>

<%= render 'form' %>

app/views/lines/show.html.erb
<p><%= link_to "Home", root_url %></p>
<h1><%= @line.name %></h1>


<p><%= link_to "Edit", edit_line_path(@line), :class => "btn btn-primary" %></p>
<p><%= link_to "Delete", line_path(@line),
                         :data => {:confirm => 'Really?',
                                   :method => 'delete'},
                         :class => 'btn btn-danger' %></p>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/stations/edit.html.erb
<p><%= link_to "Home", root_url %></p>
<h1>Edit Station</h1>

<%= render 'form' %>

app/views/stations/index.html.erb
<h1>Stations</h1>
<% @stations.each do |station| %>
  <p><%= link_to "#{station.name}", station_path(station) %></p>
<% end %>
<p><%= link_to "Add Station", new_station_path, :class => "btn btn-default" %></p>


<h1>Lines</h1>
<% @lines.each do |line| %>
  <p><%= link_to "#{line.name}", line_path(line) %></p>
<% end %>
<p><%= link_to "Add Line", new_line_path, :class => "btn btn-default" %></p>

<p><%= link_to "Add Stop", stops_path, :class => "btn btn-default" %></p>

app/views/stations/new.html.erb
<%= content_for(:title, "New station | Bus Schedule") %>

<h1>Add a Station:</h1>

<%= render 'form' %>

app/views/stations/show.html.erb
<p><%= link_to "Home", root_url %></p>
<h1><%= @station.name %></h1>


<p><%= link_to "Edit", edit_station_path(@station), :class => "btn btn-primary" %></p>
<p><%= link_to "Delete", station_path(@station),
                         :data => {:confirm => 'Really?',
                                   :method => 'delete'},
                         :class => 'btn btn-danger' %></p>

app/views/stops/_form.html.erb
<%= form_for(@station) do |f| %>
  <div class='field'>
    <% Line.all.each do |line| %>
      <%= check_box_tag "station[line_ids][]", line.id,
      @station.line_ids.include?(line.id) %>
      <%= line.name %>
    <% end %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<h1>Stop#edit</h1>
<p>Find me in app/views/stop/edit.html.erb</p>

app/views/stops/index.html.erb
<h1>Choose a Station</h1>
<% @stations.each do |station| %>
  <p><%= link_to "#{station.name}", new_stop_path(station_id: station.id) %>
<% end %>

app/views/stops/new.html.erb
<%= content_for(:title, "New stop | Bus Schedule") %>

<h1>Add lines to <%= @station.name %></h1>

<%= render "form" %>